### ISSUE TITLE
French typo

### ISSUE THREAD

**Issue by aulemahal** [turnbullerin/cf-conventions#1]
https://github.com/turnbullerin/cf-conventions/blob/850ba7612008a98646a5de6e14eda96c3d4f6abb/ch10.adoc?plain=1#L40

At this point of the discussion, I feel this comment is bit nitpicky, but I wanted to raise the issue just in case, to avoid it being forgotten before a potential merge.

The correct french would be "Titre français". (« titre » is masculine).

Thanks for the work!

**Comment by turnbullerin** [comment]
That's fair! I'll fix that thanks

**Comment by turnbullerin** [comment]
done
